#!/bin/bash
######################################################
# Simple brute force qkernel.jar build
######################################################
#
echo "brute force javac on all directories..." 
javac -nowarn -d classes/ java/*.java
javac -nowarn -d classes/ java/json/*.java
javac -nowarn -d classes/ java/servlet/*.java
javac -nowarn -d classes/ java/upload/*.java
javac -nowarn -d classes/ java/license/*.java
javac -nowarn -d classes/ java/comm/*.java
javac -nowarn -d classes/ java/classloader/*.java
echo "compiling eobuilder..." 
javac -nowarn -d classes/ -cp classes/:$CLASSPATH java/eobuilder/*.java
echo "compiling examples..." 
javac -nowarn -d classes/ -cp classes/:$CLASSPATH java/examples/model/*.java
javac -nowarn -d classes/ -cp classes/:$CLASSPATH java/examples/*.java
###

if [ -e classes/qkernel.jar ]
then
   rm classes/qkernel.jar
   echo "removed existing qkernel.jar..." 
fi
DIR=$PWD
cd classes/
jar -Mcvf qkernel.jar com/
cd $DIR
echo "done" 
