#!/bin/bash
######################################################
# run the example RestTest
######################################################
#
##### point this to your java executable ####
JAVA="/opt/install/java/bin/java"
#
$JAVA -cp ./qkernel.jar:$CLASSPATH examples/RestTest
