#!/bin/bash
######################################################
# run the EOBuilder
######################################################
#
java -cp classes/qkernel.jar:$CLASSPATH com/qkernel/eobuilder/EOBuilder $1
javac -nowarn -d classes/ -cp classes/:$CLASSPATH java/examples/model/*.java
javac -nowarn -d classes/ -cp classes/:$CLASSPATH java/examples/*.java
