#!/bin/bash
######################################################
# run the EOBuilder
######################################################
#
##### point this to your java executable ####
JAVA="/opt/install/java/bin/java"
#

$JAVA -cp ./qkernel.jar:$CLASSPATH com/qkernel/eobuilder/EOBuilder $1 $2 $3 $4
