#!/bin/bash
######################################################
# run the example shutdown process 
######################################################
#
java -cp classes/qkernel.jar:$CLASSPATH com/qkernel/examples/shutdown $1
