/* eo_account_gen.java
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import java.lang.*;
import java.sql.*;
import java.util.*;

import com.qkernel.*;


@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * An entity object for the db table account
 * 
 * 
 * @author Initially created by EntityObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class eo_account_gen extends EntityObject
{

    public final static String FIELD_ACCOUNTID = "accountId";
    public final static String FIELD_ACCOUNTCOMPANY = "accountCompany";
    public final static String FIELD_ACCOUNTADDRESS = "accountAddress";
    public final static String FIELD_ACCOUNTCITY = "accountCity";
    public final static String FIELD_ACCOUNTSTATE = "accountState";
    public final static String FIELD_ACCOUNTCOUNTRY = "accountCountry";
    public final static String FIELD_ACCOUNTPHONE = "accountPhone";
    public final static String FIELD_ACCOUNTFAX = "accountFax";
    public final static String FIELD_ACCOUNTEMAIL = "accountEmail";
    public final static String FIELD_ACCOUNTCONTACTNAME = "accountContactName";

    /****************************************************
     * find(): This method implements find by primary key
     * key for the table account.
     * If it doesn't find the object in the existing 
     * cache, it loads the necessary data from the db.
     *
     * @param id The primary key value for the record we
     *  searching for
     * @return a vo_account object, representing
     *  the record
     ****************************************************
     */
    public vo_account find(int id)
    {
        vo_account e = findInCache(id);

        if(e == null)
        {
            // Try to load cache first
            load(id);
            return(findInCache(id));
        }
        else 
        {
            // return cache value
            return(e);
        }
    }

    /*****************************************************
     * This method checks the cache for the requested item
     *
     * @param id the primary key of the record we're 
     *  looking for
     *
     * @return a vo_account that represents the 
     *  record or null, if it doesn't exist
     *
     *****************************************************
     */
    public vo_account findInCache(int id)
    {
        vo_account e = null;
        e = (vo_account)entityCache.get(new Integer(id));
        return(e);
    }

    /****************************************************
     * find(): This method implements find by primary key
     * key for the table account.
     * If it doesn't find the object in the existing 
     * cache, it loads the necessary data from the db.
     *
     * @param id The primary key value for the record we
     *  searching for
     * @return a vo_account object, representing
     *  the record
     ****************************************************
     */
    public vo_account find(String id)
    {
        vo_account e = findInCache(id);

        if(e == null)
        {
            // Try to load cache first
            load(id);
            return(findInCache(id));
        }
        else 
        {
            // return cache value
            return(e);
        }
    }

    /*****************************************************
     * This method checks the cache for the requested item
     *
     * @param id the primary key of the record we're 
     *  looking for
     *
     * @return a vo_account that represents the 
     *  record or null, if it doesn't exist
     *
     *****************************************************
     */
    public vo_account findInCache(String id)
    {
        vo_account e = null;
        e = (vo_account)entityCache.get(id);
        return(e);
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects in this Entity Object
     * @return an ArrayList of all the vo_account 
     *  objects
     *
     *****************************************************
     */
    public ArrayList find()
    {
        String query = "SELECT * FROM account ";
        ArrayList al = new ArrayList();
        executeQuery(query, "setEntity", al);
        return al;
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects based on query
     * @return an ArrayList of all the vo_account 
     *  objects
     *
     *****************************************************
     */
    public ArrayList executeQueryList(String query)
    {
        ArrayList al = new ArrayList();
        executeQuery(query, "setEntity", al);
        return al;
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects based on query
     * @return an ArrayList of all the vo_account 
     *  objects
     *
     *****************************************************
     */
    public ArrayList executeQueryList(String query, String mapper)
    {
        ArrayList al = new ArrayList();
        executeQuery(query, mapper, al);
        return al;
    }

    /****************************************************
     * executeQueryObject(): This method implements 
     * executeQuery for the table account.
     * -- and returns vo_account  
     * @param query string
     * @return a vo_account object
     ****************************************************
     */
    public vo_account executeQueryObject(String query)
    {
        Vector vec = new Vector();
        executeQuery(query, "setEntityV", vec );
        Enumeration enm = vec.elements();
        if(enm.hasMoreElements())
            return((vo_account)enm.nextElement());
        else
            return(null);
    }

    /****************************************************
     * executeQueryObject(): This method implements 
     * executeQuery for the table account.
     * -- and returns vo_account  
     * @param query string
     * @return a vo_account object
     ****************************************************
     */
    public vo_account executeQueryObject(String query, String mapper)
    {
        Vector vec = new Vector();
        executeQuery(query, mapper, vec );
        Enumeration enm = vec.elements();
        if(enm.hasMoreElements())
            return((vo_account)enm.nextElement());
        else
            return(null);
    }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_account object with the data, 
     * @param rs A result set of a query on the account table
     *****************************************************
     */
     public void setEntity(ResultSet rs, ArrayList al) throws SQLException
     {
         vo_account e = entityRow(rs);
         al.add(e);
     }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_account object with the data, 
     * @param rs A result set of a query on the account table
     *****************************************************
     */
     public void setEntityV(ResultSet rs, Vector vec) throws SQLException
     {
         vo_account e = entityRow(rs);
         vec.addElement(e);
     }

    /*****************************************************
     * This function is similar to the setEntity() method.
     * It takes the current row in a ResultSet,
     * creates a vo_account object with the data, 
     * but instead of placing it in the cache,
     * it places it in the ArrayList that is passed in.
    *
     * @param al An ArrayList to place the resulting vo_account object into.
     * @param rs A result set of a query on the account table
     * @see #setEntity()
     ****************************************************
     */
    public void setEntityC(ResultSet rs) throws SQLException
    {
        vo_account e = entityRow(rs);
        entityCache.put(new Integer(e.accountId), e);
     }

    /****************************************************
     * This function maps an SQL row to a Value Object
     *
     * @param rs a ResultSet that contains the record to be mapped
     * @return a vo_account value object
     ****************************************************
     */
    public vo_account entityRow(ResultSet rs) throws SQLException
    {
        vo_account e = new vo_account();
        e.accountId= rs.getInt(FIELD_ACCOUNTID);
        e.accountCompany= rs.getString(FIELD_ACCOUNTCOMPANY);
        e.accountAddress= rs.getString(FIELD_ACCOUNTADDRESS);
        e.accountCity= rs.getString(FIELD_ACCOUNTCITY);
        e.accountState= rs.getString(FIELD_ACCOUNTSTATE);
        e.accountCountry= rs.getString(FIELD_ACCOUNTCOUNTRY);
        e.accountPhone= rs.getString(FIELD_ACCOUNTPHONE);
        e.accountFax= rs.getString(FIELD_ACCOUNTFAX);
        e.accountEmail= rs.getString(FIELD_ACCOUNTEMAIL);
        e.accountContactName= rs.getString(FIELD_ACCOUNTCONTACTNAME);
        return(e);
    }

    /****************************************************
     * This method inserts a new record into the table,
     * but DOES NOT return the new ID or a reference object
     * @param vo_account a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insert(vo_account e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO account(");
        qsb.append(FIELD_ACCOUNTCOMPANY+",");
        qsb.append(FIELD_ACCOUNTADDRESS+",");
        qsb.append(FIELD_ACCOUNTCITY+",");
        qsb.append(FIELD_ACCOUNTSTATE+",");
        qsb.append(FIELD_ACCOUNTCOUNTRY+",");
        qsb.append(FIELD_ACCOUNTPHONE+",");
        qsb.append(FIELD_ACCOUNTFAX+",");
        qsb.append(FIELD_ACCOUNTEMAIL+",");
        qsb.append(FIELD_ACCOUNTCONTACTNAME+")");
        qsb.append("VALUES(");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCompany)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountAddress)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCity)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountState)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCountry)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountPhone)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountFax)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountEmail)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountContactName)).append("')");


        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * using the local entityQueue
     * @param vo_account a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insertQueue(vo_account e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO account(");
        qsb.append(FIELD_ACCOUNTCOMPANY+",");
        qsb.append(FIELD_ACCOUNTADDRESS+",");
        qsb.append(FIELD_ACCOUNTCITY+",");
        qsb.append(FIELD_ACCOUNTSTATE+",");
        qsb.append(FIELD_ACCOUNTCOUNTRY+",");
        qsb.append(FIELD_ACCOUNTPHONE+",");
        qsb.append(FIELD_ACCOUNTFAX+",");
        qsb.append(FIELD_ACCOUNTEMAIL+",");
        qsb.append(FIELD_ACCOUNTCONTACTNAME+")");
        qsb.append("VALUES(");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCompany)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountAddress)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCity)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountState)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCountry)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountPhone)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountFax)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountEmail)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountContactName)).append("')");


        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * AND returns a reference object with the new
     * auto-generated PK;
     *
     * @param vo_account a value object to be written to the DB
      * @return a vo_account object that represents
     *  the original object, with the addition of the primary key
     * @see #insert()
     ****************************************************
     */
    public vo_account insert2(vo_account e)
    {
        vo_account e1=(vo_account) e.clone();

        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO account(");
        qsb.append(FIELD_ACCOUNTCOMPANY+",");
        qsb.append(FIELD_ACCOUNTADDRESS+",");
        qsb.append(FIELD_ACCOUNTCITY+",");
        qsb.append(FIELD_ACCOUNTSTATE+",");
        qsb.append(FIELD_ACCOUNTCOUNTRY+",");
        qsb.append(FIELD_ACCOUNTPHONE+",");
        qsb.append(FIELD_ACCOUNTFAX+",");
        qsb.append(FIELD_ACCOUNTEMAIL+",");
        qsb.append(FIELD_ACCOUNTCONTACTNAME+")");
        qsb.append("VALUES(");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCompany)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountAddress)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCity)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountState)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountCountry)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountPhone)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountFax)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountEmail)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.accountContactName)).append("')");


        try
        {
            Connection conn    = entityDbPool.getConnection();
            Statement stmt     = conn.createStatement();
            stmt.executeUpdate(qsb.toString());
            //------------------------------------------------------------------
            // Retrieve new AUTO_INCREMENT accountId 
            //------------------------------------------------------------------
            ResultSet r = stmt.executeQuery("SELECT LAST_INSERT_ID() AS cId");
            r.next();
            e1.accountId= r.getInt("cId");
            stmt.close();
            entityDbPool.freeConnection(conn);
        }
        catch(Exception ept)
        {
            daemon.eventLog.sendMessage(ept);
        }
        return(e1);
    }

    /****************************************************
     * This function updates the record in the database
     * who's primary key matches the 
     * accountId value of the passed-in 
     * vo_account object.
     *
     * @param e a vo_account object
     ****************************************************
     */
    public void update(vo_account e)
    {
        StringBuffer qsb=new StringBuffer();
        qsb.append("UPDATE account ").append("SET ");
        qsb.append(FIELD_ACCOUNTCOMPANY+"='").append(SqlSafe.sqlSafe( e.accountCompany)).append("',");
        qsb.append(FIELD_ACCOUNTADDRESS+"='").append(SqlSafe.sqlSafe( e.accountAddress)).append("',");
        qsb.append(FIELD_ACCOUNTCITY+"='").append(SqlSafe.sqlSafe( e.accountCity)).append("',");
        qsb.append(FIELD_ACCOUNTSTATE+"='").append(SqlSafe.sqlSafe( e.accountState)).append("',");
        qsb.append(FIELD_ACCOUNTCOUNTRY+"='").append(SqlSafe.sqlSafe( e.accountCountry)).append("',");
        qsb.append(FIELD_ACCOUNTPHONE+"='").append(SqlSafe.sqlSafe( e.accountPhone)).append("',");
        qsb.append(FIELD_ACCOUNTFAX+"='").append(SqlSafe.sqlSafe( e.accountFax)).append("',");
        qsb.append(FIELD_ACCOUNTEMAIL+"='").append(SqlSafe.sqlSafe( e.accountEmail)).append("',");
        qsb.append(FIELD_ACCOUNTCONTACTNAME+"='").append(SqlSafe.sqlSafe( e.accountContactName)).append("'");
        qsb.append(" WHERE ");
                qsb.append("accountId="+e.accountId);

        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This function updates the record in the database
     * who's primary key matches the 
     * accountId value of the passed-in 
     * vo_account object.
     *
     * @param e a vo_account object
     ****************************************************
     */
    public void updateQueue(vo_account e)
    {
        StringBuffer qsb=new StringBuffer();
        qsb.append("UPDATE account ").append("SET ");
        qsb.append(FIELD_ACCOUNTCOMPANY+"='").append(SqlSafe.sqlSafe( e.accountCompany)).append("',");
        qsb.append(FIELD_ACCOUNTADDRESS+"='").append(SqlSafe.sqlSafe( e.accountAddress)).append("',");
        qsb.append(FIELD_ACCOUNTCITY+"='").append(SqlSafe.sqlSafe( e.accountCity)).append("',");
        qsb.append(FIELD_ACCOUNTSTATE+"='").append(SqlSafe.sqlSafe( e.accountState)).append("',");
        qsb.append(FIELD_ACCOUNTCOUNTRY+"='").append(SqlSafe.sqlSafe( e.accountCountry)).append("',");
        qsb.append(FIELD_ACCOUNTPHONE+"='").append(SqlSafe.sqlSafe( e.accountPhone)).append("',");
        qsb.append(FIELD_ACCOUNTFAX+"='").append(SqlSafe.sqlSafe( e.accountFax)).append("',");
        qsb.append(FIELD_ACCOUNTEMAIL+"='").append(SqlSafe.sqlSafe( e.accountEmail)).append("',");
        qsb.append(FIELD_ACCOUNTCONTACTNAME+"='").append(SqlSafe.sqlSafe( e.accountContactName)).append("'");
        qsb.append(" WHERE ");
                qsb.append("accountId="+e.accountId);

        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * delete(id): This method deletes the object in the
     * who's primary ket matches the value passed in
     * 
     * @param id a Int representing the primary key
     ****************************************************
     */
    public void delete(int id)
    {
        String query;
        query="DELETE FROM account WHERE accountId="+id;
        executeUpdate(query);
    }

    /****************************************************
     * This is the default load method that is called by
     * the container at startup
     ****************************************************
     */
    public void load()
    {
         //This is empty for now

    }

    /****************************************************
     * This function loads an individual record into the
     * cache
     *
     * @param id The primary key to use for record lookup
     ****************************************************
     */
    public void load(int id)
    {
       String qs=
           "SELECT * FROM account WHERE accountId="+id;

       executeQuery(qs,"setEntityC");
    }

    /****************************************************
     * This function loads an individual record into the
     * cache
     *
     * @param id The  key to use for record lookup
     ****************************************************
     */
    public void load(String id)
    {
         //Override this method to implement cache scheme

    }

    /****************************************************
     * This function returns the number of records
     * in the table represented by this entity. 
     * 
     * @return The number of records in the table
     ****************************************************
     */
    public int getCount()
    {
        int count=0;
        String qs=
            "SELECT COUNT(accountId) AS Count FROM account ";
        ResultSet r=executeQuery(qs);
        try
        {
            r.next();
            count=r.getInt("Count");
            closeResultSet(r);
        }
        catch(Exception e)
         {
            daemon.event_log.sendMessage("Can't retrieve ResultSet because: "+e.getMessage());
        }
        return(count);
    }

    /****************************************************
     * This function is called by the daemon when this 
     * Entity Object is initialized
     * Sub-class should invoke super.init() then:
     * entityCache.start(t)
     * useLocalEntityQueue() (if you want a local queue)
     ****************************************************
     */
    public void init()
    {
        entityQueue.start();          // Start Global Entity Queue
        //entityCache.start(30);      // Start Entity Cache
        //useLocalEntityQueue();      // Set and Start Local Entity Queue
    }

}

