/* eo_media_gen.java
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import java.lang.*;
import java.sql.*;
import java.util.*;

import com.qkernel.*;


@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * An entity object for the db table media
 * 
 * 
 * @author Initially created by EntityObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class eo_media_gen extends EntityObject
{

    public final static String FIELD_MEDIAID = "mediaId";
    public final static String FIELD_USERID = "userId";
    public final static String FIELD_MEDIAFILE = "mediaFile";
    public final static String FIELD_MEDIASOURCE = "mediaSource";
    public final static String FIELD_MEDIAARTIST = "mediaArtist";
    public final static String FIELD_MEDIATITLE = "mediaTitle";
    public final static String FIELD_MEDIAYEAR = "mediaYear";
    public final static String FIELD_MEDIADURATION = "mediaDuration";
    public final static String FIELD_MEDIACREATED = "mediaCreated";
    public final static String FIELD_MEDIAMODIFIED = "mediaModified";
    public final static String FIELD_MEDIASTATUS = "mediaStatus";

    /****************************************************
     * find(): This method implements find by primary key
     * key for the table media.
     * If it doesn't find the object in the existing 
     * cache, it loads the necessary data from the db.
     *
     * @param id The primary key value for the record we
     *  searching for
     * @return a vo_media object, representing
     *  the record
     ****************************************************
     */
    public vo_media find(int id)
    {
        vo_media e = findInCache(id);

        if(e == null)
        {
            // Try to load cache first
            load(id);
            return(findInCache(id));
        }
        else 
        {
            // return cache value
            return(e);
        }
    }

    /*****************************************************
     * This method checks the cache for the requested item
     *
     * @param id the primary key of the record we're 
     *  looking for
     *
     * @return a vo_media that represents the 
     *  record or null, if it doesn't exist
     *
     *****************************************************
     */
    public vo_media findInCache(int id)
    {
        vo_media e = null;
        e = (vo_media)entityCache.get(new Integer(id));
        return(e);
    }

    /****************************************************
     * find(): This method implements find by primary key
     * key for the table media.
     * If it doesn't find the object in the existing 
     * cache, it loads the necessary data from the db.
     *
     * @param id The primary key value for the record we
     *  searching for
     * @return a vo_media object, representing
     *  the record
     ****************************************************
     */
    public vo_media find(String id)
    {
        vo_media e = findInCache(id);

        if(e == null)
        {
            // Try to load cache first
            load(id);
            return(findInCache(id));
        }
        else 
        {
            // return cache value
            return(e);
        }
    }

    /*****************************************************
     * This method checks the cache for the requested item
     *
     * @param id the primary key of the record we're 
     *  looking for
     *
     * @return a vo_media that represents the 
     *  record or null, if it doesn't exist
     *
     *****************************************************
     */
    public vo_media findInCache(String id)
    {
        vo_media e = null;
        e = (vo_media)entityCache.get(id);
        return(e);
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects in this Entity Object
     * @return an ArrayList of all the vo_media 
     *  objects
     *
     *****************************************************
     */
    public ArrayList find()
    {
        String query = "SELECT * FROM media ";
        ArrayList al = new ArrayList();
        executeQuery(query, "setEntity", al);
        return al;
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects based on query
     * @return an ArrayList of all the vo_media 
     *  objects
     *
     *****************************************************
     */
    public ArrayList executeQueryList(String query)
    {
        ArrayList al = new ArrayList();
        executeQuery(query, "setEntity", al);
        return al;
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects based on query
     * @return an ArrayList of all the vo_media 
     *  objects
     *
     *****************************************************
     */
    public ArrayList executeQueryList(String query, String mapper)
    {
        ArrayList al = new ArrayList();
        executeQuery(query, mapper, al);
        return al;
    }

    /****************************************************
     * executeQueryObject(): This method implements 
     * executeQuery for the table media.
     * -- and returns vo_media  
     * @param query string
     * @return a vo_media object
     ****************************************************
     */
    public vo_media executeQueryObject(String query)
    {
        Vector vec = new Vector();
        executeQuery(query, "setEntityV", vec );
        Enumeration enm = vec.elements();
        if(enm.hasMoreElements())
            return((vo_media)enm.nextElement());
        else
            return(null);
    }

    /****************************************************
     * executeQueryObject(): This method implements 
     * executeQuery for the table media.
     * -- and returns vo_media  
     * @param query string
     * @return a vo_media object
     ****************************************************
     */
    public vo_media executeQueryObject(String query, String mapper)
    {
        Vector vec = new Vector();
        executeQuery(query, mapper, vec );
        Enumeration enm = vec.elements();
        if(enm.hasMoreElements())
            return((vo_media)enm.nextElement());
        else
            return(null);
    }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_media object with the data, 
     * @param rs A result set of a query on the media table
     *****************************************************
     */
     public void setEntity(ResultSet rs, ArrayList al) throws SQLException
     {
         vo_media e = entityRow(rs);
         al.add(e);
     }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_media object with the data, 
     * @param rs A result set of a query on the media table
     *****************************************************
     */
     public void setEntityV(ResultSet rs, Vector vec) throws SQLException
     {
         vo_media e = entityRow(rs);
         vec.addElement(e);
     }

    /*****************************************************
     * This function is similar to the setEntity() method.
     * It takes the current row in a ResultSet,
     * creates a vo_media object with the data, 
     * but instead of placing it in the cache,
     * it places it in the ArrayList that is passed in.
    *
     * @param al An ArrayList to place the resulting vo_media object into.
     * @param rs A result set of a query on the media table
     * @see #setEntity()
     ****************************************************
     */
    public void setEntityC(ResultSet rs) throws SQLException
    {
        vo_media e = entityRow(rs);
        entityCache.put(new Integer(e.mediaId), e);
     }

    /****************************************************
     * This function maps an SQL row to a Value Object
     *
     * @param rs a ResultSet that contains the record to be mapped
     * @return a vo_media value object
     ****************************************************
     */
    public vo_media entityRow(ResultSet rs) throws SQLException
    {
        vo_media e = new vo_media();
        e.mediaId= rs.getInt(FIELD_MEDIAID);
        e.userId= rs.getInt(FIELD_USERID);
        e.mediaFile= rs.getString(FIELD_MEDIAFILE);
        e.mediaSource= rs.getString(FIELD_MEDIASOURCE);
        e.mediaArtist= rs.getString(FIELD_MEDIAARTIST);
        e.mediaTitle= rs.getString(FIELD_MEDIATITLE);
        e.mediaYear= rs.getString(FIELD_MEDIAYEAR);
        e.mediaDuration= rs.getString(FIELD_MEDIADURATION);
        e.mediaCreated= rs.getString(FIELD_MEDIACREATED);
        e.mediaModified= rs.getString(FIELD_MEDIAMODIFIED);
        e.mediaStatus= rs.getString(FIELD_MEDIASTATUS);
        return(e);
    }

    /****************************************************
     * This method inserts a new record into the table,
     * but DOES NOT return the new ID or a reference object
     * @param vo_media a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insert(vo_media e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO media(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_MEDIAFILE+",");
        qsb.append(FIELD_MEDIASOURCE+",");
        qsb.append(FIELD_MEDIAARTIST+",");
        qsb.append(FIELD_MEDIATITLE+",");
        qsb.append(FIELD_MEDIAYEAR+",");
        qsb.append(FIELD_MEDIADURATION+",");
        qsb.append(FIELD_MEDIACREATED+",");
        qsb.append(FIELD_MEDIAMODIFIED+",");
        qsb.append(FIELD_MEDIASTATUS+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaFile)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaSource)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaArtist)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaTitle)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaYear)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaDuration)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaCreated)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaModified)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaStatus)).append("')");


        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * using the local entityQueue
     * @param vo_media a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insertQueue(vo_media e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO media(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_MEDIAFILE+",");
        qsb.append(FIELD_MEDIASOURCE+",");
        qsb.append(FIELD_MEDIAARTIST+",");
        qsb.append(FIELD_MEDIATITLE+",");
        qsb.append(FIELD_MEDIAYEAR+",");
        qsb.append(FIELD_MEDIADURATION+",");
        qsb.append(FIELD_MEDIACREATED+",");
        qsb.append(FIELD_MEDIAMODIFIED+",");
        qsb.append(FIELD_MEDIASTATUS+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaFile)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaSource)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaArtist)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaTitle)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaYear)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaDuration)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaCreated)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaModified)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaStatus)).append("')");


        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * AND returns a reference object with the new
     * auto-generated PK;
     *
     * @param vo_media a value object to be written to the DB
      * @return a vo_media object that represents
     *  the original object, with the addition of the primary key
     * @see #insert()
     ****************************************************
     */
    public vo_media insert2(vo_media e)
    {
        vo_media e1=(vo_media) e.clone();

        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO media(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_MEDIAFILE+",");
        qsb.append(FIELD_MEDIASOURCE+",");
        qsb.append(FIELD_MEDIAARTIST+",");
        qsb.append(FIELD_MEDIATITLE+",");
        qsb.append(FIELD_MEDIAYEAR+",");
        qsb.append(FIELD_MEDIADURATION+",");
        qsb.append(FIELD_MEDIACREATED+",");
        qsb.append(FIELD_MEDIAMODIFIED+",");
        qsb.append(FIELD_MEDIASTATUS+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaFile)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaSource)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaArtist)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaTitle)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaYear)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaDuration)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaCreated)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaModified)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.mediaStatus)).append("')");


        try
        {
            Connection conn    = entityDbPool.getConnection();
            Statement stmt     = conn.createStatement();
            stmt.executeUpdate(qsb.toString());
            //------------------------------------------------------------------
            // Retrieve new AUTO_INCREMENT mediaId 
            //------------------------------------------------------------------
            ResultSet r = stmt.executeQuery("SELECT LAST_INSERT_ID() AS cId");
            r.next();
            e1.mediaId= r.getInt("cId");
            stmt.close();
            entityDbPool.freeConnection(conn);
        }
        catch(Exception ept)
        {
            daemon.eventLog.sendMessage(ept);
        }
        return(e1);
    }

    /****************************************************
     * This function updates the record in the database
     * who's primary key matches the 
     * mediaId value of the passed-in 
     * vo_media object.
     *
     * @param e a vo_media object
     ****************************************************
     */
    public void update(vo_media e)
    {
        StringBuffer qsb=new StringBuffer();
        qsb.append("UPDATE media ").append("SET ");
        qsb.append(FIELD_USERID+"=").append(e.userId).append(",");
        qsb.append(FIELD_MEDIAFILE+"='").append(SqlSafe.sqlSafe( e.mediaFile)).append("',");
        qsb.append(FIELD_MEDIASOURCE+"='").append(SqlSafe.sqlSafe( e.mediaSource)).append("',");
        qsb.append(FIELD_MEDIAARTIST+"='").append(SqlSafe.sqlSafe( e.mediaArtist)).append("',");
        qsb.append(FIELD_MEDIATITLE+"='").append(SqlSafe.sqlSafe( e.mediaTitle)).append("',");
        qsb.append(FIELD_MEDIAYEAR+"='").append(SqlSafe.sqlSafe( e.mediaYear)).append("',");
        qsb.append(FIELD_MEDIADURATION+"='").append(SqlSafe.sqlSafe( e.mediaDuration)).append("',");
        qsb.append(FIELD_MEDIACREATED+"='").append(SqlSafe.sqlSafe( e.mediaCreated)).append("',");
        qsb.append(FIELD_MEDIAMODIFIED+"='").append(SqlSafe.sqlSafe( e.mediaModified)).append("',");
        qsb.append(FIELD_MEDIASTATUS+"='").append(SqlSafe.sqlSafe( e.mediaStatus)).append("'");
        qsb.append(" WHERE ");
                qsb.append("mediaId="+e.mediaId);

        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This function updates the record in the database
     * who's primary key matches the 
     * mediaId value of the passed-in 
     * vo_media object.
     *
     * @param e a vo_media object
     ****************************************************
     */
    public void updateQueue(vo_media e)
    {
        StringBuffer qsb=new StringBuffer();
        qsb.append("UPDATE media ").append("SET ");
        qsb.append(FIELD_USERID+"=").append(e.userId).append(",");
        qsb.append(FIELD_MEDIAFILE+"='").append(SqlSafe.sqlSafe( e.mediaFile)).append("',");
        qsb.append(FIELD_MEDIASOURCE+"='").append(SqlSafe.sqlSafe( e.mediaSource)).append("',");
        qsb.append(FIELD_MEDIAARTIST+"='").append(SqlSafe.sqlSafe( e.mediaArtist)).append("',");
        qsb.append(FIELD_MEDIATITLE+"='").append(SqlSafe.sqlSafe( e.mediaTitle)).append("',");
        qsb.append(FIELD_MEDIAYEAR+"='").append(SqlSafe.sqlSafe( e.mediaYear)).append("',");
        qsb.append(FIELD_MEDIADURATION+"='").append(SqlSafe.sqlSafe( e.mediaDuration)).append("',");
        qsb.append(FIELD_MEDIACREATED+"='").append(SqlSafe.sqlSafe( e.mediaCreated)).append("',");
        qsb.append(FIELD_MEDIAMODIFIED+"='").append(SqlSafe.sqlSafe( e.mediaModified)).append("',");
        qsb.append(FIELD_MEDIASTATUS+"='").append(SqlSafe.sqlSafe( e.mediaStatus)).append("'");
        qsb.append(" WHERE ");
                qsb.append("mediaId="+e.mediaId);

        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * delete(id): This method deletes the object in the
     * who's primary ket matches the value passed in
     * 
     * @param id a Int representing the primary key
     ****************************************************
     */
    public void delete(int id)
    {
        String query;
        query="DELETE FROM media WHERE mediaId="+id;
        executeUpdate(query);
    }

    /****************************************************
     * This is the default load method that is called by
     * the container at startup
     ****************************************************
     */
    public void load()
    {
         //This is empty for now

    }

    /****************************************************
     * This function loads an individual record into the
     * cache
     *
     * @param id The primary key to use for record lookup
     ****************************************************
     */
    public void load(int id)
    {
       String qs=
           "SELECT * FROM media WHERE mediaId="+id;

       executeQuery(qs,"setEntityC");
    }

    /****************************************************
     * This function loads an individual record into the
     * cache
     *
     * @param id The  key to use for record lookup
     ****************************************************
     */
    public void load(String id)
    {
         //Override this method to implement cache scheme

    }

    /****************************************************
     * This function returns the number of records
     * in the table represented by this entity. 
     * 
     * @return The number of records in the table
     ****************************************************
     */
    public int getCount()
    {
        int count=0;
        String qs=
            "SELECT COUNT(mediaId) AS Count FROM media ";
        ResultSet r=executeQuery(qs);
        try
        {
            r.next();
            count=r.getInt("Count");
            closeResultSet(r);
        }
        catch(Exception e)
         {
            daemon.event_log.sendMessage("Can't retrieve ResultSet because: "+e.getMessage());
        }
        return(count);
    }

    /****************************************************
     * This function is called by the daemon when this 
     * Entity Object is initialized
     * Sub-class should invoke super.init() then:
     * entityCache.start(t)
     * useLocalEntityQueue() (if you want a local queue)
     ****************************************************
     */
    public void init()
    {
        entityQueue.start();          // Start Global Entity Queue
        //entityCache.start(30);      // Start Entity Cache
        //useLocalEntityQueue();      // Set and Start Local Entity Queue
    }

}

