/* eo_upload_gen.java
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import java.lang.*;
import java.sql.*;
import java.util.*;

import com.qkernel.*;


@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * An entity object for the db table upload
 * 
 * 
 * @author Initially created by EntityObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class eo_upload_gen extends EntityObject
{

    public final static String FIELD_UPLOADID = "uploadId";
    public final static String FIELD_USERID = "userId";
    public final static String FIELD_UPLOADMETADATA = "uploadMetaData";
    public final static String FIELD_UPLOADSOURCE = "uploadSource";
    public final static String FIELD_UPLOADCREATED = "uploadCreated";
    public final static String FIELD_UPLOADMODIFIED = "uploadModified";
    public final static String FIELD_UPLOADSTATUS = "uploadStatus";

    /****************************************************
     * find(): This method implements find by primary key
     * key for the table upload.
     * If it doesn't find the object in the existing 
     * cache, it loads the necessary data from the db.
     *
     * @param id The primary key value for the record we
     *  searching for
     * @return a vo_upload object, representing
     *  the record
     ****************************************************
     */
    public vo_upload find(int id)
    {
        vo_upload e = findInCache(id);

        if(e == null)
        {
            // Try to load cache first
            load(id);
            return(findInCache(id));
        }
        else 
        {
            // return cache value
            return(e);
        }
    }

    /*****************************************************
     * This method checks the cache for the requested item
     *
     * @param id the primary key of the record we're 
     *  looking for
     *
     * @return a vo_upload that represents the 
     *  record or null, if it doesn't exist
     *
     *****************************************************
     */
    public vo_upload findInCache(int id)
    {
        vo_upload e = null;
        e = (vo_upload)entityCache.get(new Integer(id));
        return(e);
    }

    /****************************************************
     * find(): This method implements find by primary key
     * key for the table upload.
     * If it doesn't find the object in the existing 
     * cache, it loads the necessary data from the db.
     *
     * @param id The primary key value for the record we
     *  searching for
     * @return a vo_upload object, representing
     *  the record
     ****************************************************
     */
    public vo_upload find(String id)
    {
        vo_upload e = findInCache(id);

        if(e == null)
        {
            // Try to load cache first
            load(id);
            return(findInCache(id));
        }
        else 
        {
            // return cache value
            return(e);
        }
    }

    /*****************************************************
     * This method checks the cache for the requested item
     *
     * @param id the primary key of the record we're 
     *  looking for
     *
     * @return a vo_upload that represents the 
     *  record or null, if it doesn't exist
     *
     *****************************************************
     */
    public vo_upload findInCache(String id)
    {
        vo_upload e = null;
        e = (vo_upload)entityCache.get(id);
        return(e);
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects in this Entity Object
     * @return an ArrayList of all the vo_upload 
     *  objects
     *
     *****************************************************
     */
    public ArrayList find()
    {
        String query = "SELECT * FROM upload ";
        ArrayList al = new ArrayList();
        executeQuery(query, "setEntity", al);
        return al;
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects based on query
     * @return an ArrayList of all the vo_upload 
     *  objects
     *
     *****************************************************
     */
    public ArrayList executeQueryList(String query)
    {
        ArrayList al = new ArrayList();
        executeQuery(query, "setEntity", al);
        return al;
    }

    /*****************************************************
     * This function returns an ArrayList  of all Value 
     * Objects based on query
     * @return an ArrayList of all the vo_upload 
     *  objects
     *
     *****************************************************
     */
    public ArrayList executeQueryList(String query, String mapper)
    {
        ArrayList al = new ArrayList();
        executeQuery(query, mapper, al);
        return al;
    }

    /****************************************************
     * executeQueryObject(): This method implements 
     * executeQuery for the table upload.
     * -- and returns vo_upload  
     * @param query string
     * @return a vo_upload object
     ****************************************************
     */
    public vo_upload executeQueryObject(String query)
    {
        Vector vec = new Vector();
        executeQuery(query, "setEntityV", vec );
        Enumeration enm = vec.elements();
        if(enm.hasMoreElements())
            return((vo_upload)enm.nextElement());
        else
            return(null);
    }

    /****************************************************
     * executeQueryObject(): This method implements 
     * executeQuery for the table upload.
     * -- and returns vo_upload  
     * @param query string
     * @return a vo_upload object
     ****************************************************
     */
    public vo_upload executeQueryObject(String query, String mapper)
    {
        Vector vec = new Vector();
        executeQuery(query, mapper, vec );
        Enumeration enm = vec.elements();
        if(enm.hasMoreElements())
            return((vo_upload)enm.nextElement());
        else
            return(null);
    }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_upload object with the data, 
     * @param rs A result set of a query on the upload table
     *****************************************************
     */
     public void setEntity(ResultSet rs, ArrayList al) throws SQLException
     {
         vo_upload e = entityRow(rs);
         al.add(e);
     }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_upload object with the data, 
     * @param rs A result set of a query on the upload table
     *****************************************************
     */
     public void setEntityV(ResultSet rs, Vector vec) throws SQLException
     {
         vo_upload e = entityRow(rs);
         vec.addElement(e);
     }

    /*****************************************************
     * This function is similar to the setEntity() method.
     * It takes the current row in a ResultSet,
     * creates a vo_upload object with the data, 
     * but instead of placing it in the cache,
     * it places it in the ArrayList that is passed in.
    *
     * @param al An ArrayList to place the resulting vo_upload object into.
     * @param rs A result set of a query on the upload table
     * @see #setEntity()
     ****************************************************
     */
    public void setEntityC(ResultSet rs) throws SQLException
    {
        vo_upload e = entityRow(rs);
        entityCache.put(new Integer(e.uploadId), e);
     }

    /****************************************************
     * This function maps an SQL row to a Value Object
     *
     * @param rs a ResultSet that contains the record to be mapped
     * @return a vo_upload value object
     ****************************************************
     */
    public vo_upload entityRow(ResultSet rs) throws SQLException
    {
        vo_upload e = new vo_upload();
        e.uploadId= rs.getInt(FIELD_UPLOADID);
        e.userId= rs.getInt(FIELD_USERID);
        e.uploadMetaData= rs.getString(FIELD_UPLOADMETADATA);
        e.uploadSource= rs.getString(FIELD_UPLOADSOURCE);
        e.uploadCreated= rs.getString(FIELD_UPLOADCREATED);
        e.uploadModified= rs.getString(FIELD_UPLOADMODIFIED);
        e.uploadStatus= rs.getString(FIELD_UPLOADSTATUS);
        return(e);
    }

    /****************************************************
     * This method inserts a new record into the table,
     * but DOES NOT return the new ID or a reference object
     * @param vo_upload a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insert(vo_upload e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO upload(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_UPLOADMETADATA+",");
        qsb.append(FIELD_UPLOADSOURCE+",");
        qsb.append(FIELD_UPLOADCREATED+",");
        qsb.append(FIELD_UPLOADMODIFIED+",");
        qsb.append(FIELD_UPLOADSTATUS+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadMetaData)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadSource)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadCreated)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadModified)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadStatus)).append("')");


        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * using the local entityQueue
     * @param vo_upload a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insertQueue(vo_upload e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO upload(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_UPLOADMETADATA+",");
        qsb.append(FIELD_UPLOADSOURCE+",");
        qsb.append(FIELD_UPLOADCREATED+",");
        qsb.append(FIELD_UPLOADMODIFIED+",");
        qsb.append(FIELD_UPLOADSTATUS+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadMetaData)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadSource)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadCreated)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadModified)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadStatus)).append("')");


        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * AND returns a reference object with the new
     * auto-generated PK;
     *
     * @param vo_upload a value object to be written to the DB
      * @return a vo_upload object that represents
     *  the original object, with the addition of the primary key
     * @see #insert()
     ****************************************************
     */
    public vo_upload insert2(vo_upload e)
    {
        vo_upload e1=(vo_upload) e.clone();

        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO upload(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_UPLOADMETADATA+",");
        qsb.append(FIELD_UPLOADSOURCE+",");
        qsb.append(FIELD_UPLOADCREATED+",");
        qsb.append(FIELD_UPLOADMODIFIED+",");
        qsb.append(FIELD_UPLOADSTATUS+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadMetaData)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadSource)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadCreated)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadModified)).append("',");
        qsb.append("'").append(SqlSafe.sqlSafe( e.uploadStatus)).append("')");


        try
        {
            Connection conn    = entityDbPool.getConnection();
            Statement stmt     = conn.createStatement();
            stmt.executeUpdate(qsb.toString());
            //------------------------------------------------------------------
            // Retrieve new AUTO_INCREMENT uploadId 
            //------------------------------------------------------------------
            ResultSet r = stmt.executeQuery("SELECT LAST_INSERT_ID() AS cId");
            r.next();
            e1.uploadId= r.getInt("cId");
            stmt.close();
            entityDbPool.freeConnection(conn);
        }
        catch(Exception ept)
        {
            daemon.eventLog.sendMessage(ept);
        }
        return(e1);
    }

    /****************************************************
     * This function updates the record in the database
     * who's primary key matches the 
     * uploadId value of the passed-in 
     * vo_upload object.
     *
     * @param e a vo_upload object
     ****************************************************
     */
    public void update(vo_upload e)
    {
        StringBuffer qsb=new StringBuffer();
        qsb.append("UPDATE upload ").append("SET ");
        qsb.append(FIELD_USERID+"=").append(e.userId).append(",");
        qsb.append(FIELD_UPLOADMETADATA+"='").append(SqlSafe.sqlSafe( e.uploadMetaData)).append("',");
        qsb.append(FIELD_UPLOADSOURCE+"='").append(SqlSafe.sqlSafe( e.uploadSource)).append("',");
        qsb.append(FIELD_UPLOADCREATED+"='").append(SqlSafe.sqlSafe( e.uploadCreated)).append("',");
        qsb.append(FIELD_UPLOADMODIFIED+"='").append(SqlSafe.sqlSafe( e.uploadModified)).append("',");
        qsb.append(FIELD_UPLOADSTATUS+"='").append(SqlSafe.sqlSafe( e.uploadStatus)).append("'");
        qsb.append(" WHERE ");
                qsb.append("uploadId="+e.uploadId);

        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This function updates the record in the database
     * who's primary key matches the 
     * uploadId value of the passed-in 
     * vo_upload object.
     *
     * @param e a vo_upload object
     ****************************************************
     */
    public void updateQueue(vo_upload e)
    {
        StringBuffer qsb=new StringBuffer();
        qsb.append("UPDATE upload ").append("SET ");
        qsb.append(FIELD_USERID+"=").append(e.userId).append(",");
        qsb.append(FIELD_UPLOADMETADATA+"='").append(SqlSafe.sqlSafe( e.uploadMetaData)).append("',");
        qsb.append(FIELD_UPLOADSOURCE+"='").append(SqlSafe.sqlSafe( e.uploadSource)).append("',");
        qsb.append(FIELD_UPLOADCREATED+"='").append(SqlSafe.sqlSafe( e.uploadCreated)).append("',");
        qsb.append(FIELD_UPLOADMODIFIED+"='").append(SqlSafe.sqlSafe( e.uploadModified)).append("',");
        qsb.append(FIELD_UPLOADSTATUS+"='").append(SqlSafe.sqlSafe( e.uploadStatus)).append("'");
        qsb.append(" WHERE ");
                qsb.append("uploadId="+e.uploadId);

        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * delete(id): This method deletes the object in the
     * who's primary ket matches the value passed in
     * 
     * @param id a Int representing the primary key
     ****************************************************
     */
    public void delete(int id)
    {
        String query;
        query="DELETE FROM upload WHERE uploadId="+id;
        executeUpdate(query);
    }

    /****************************************************
     * This is the default load method that is called by
     * the container at startup
     ****************************************************
     */
    public void load()
    {
         //This is empty for now

    }

    /****************************************************
     * This function loads an individual record into the
     * cache
     *
     * @param id The primary key to use for record lookup
     ****************************************************
     */
    public void load(int id)
    {
       String qs=
           "SELECT * FROM upload WHERE uploadId="+id;

       executeQuery(qs,"setEntityC");
    }

    /****************************************************
     * This function loads an individual record into the
     * cache
     *
     * @param id The  key to use for record lookup
     ****************************************************
     */
    public void load(String id)
    {
         //Override this method to implement cache scheme

    }

    /****************************************************
     * This function returns the number of records
     * in the table represented by this entity. 
     * 
     * @return The number of records in the table
     ****************************************************
     */
    public int getCount()
    {
        int count=0;
        String qs=
            "SELECT COUNT(uploadId) AS Count FROM upload ";
        ResultSet r=executeQuery(qs);
        try
        {
            r.next();
            count=r.getInt("Count");
            closeResultSet(r);
        }
        catch(Exception e)
         {
            daemon.event_log.sendMessage("Can't retrieve ResultSet because: "+e.getMessage());
        }
        return(count);
    }

    /****************************************************
     * This function is called by the daemon when this 
     * Entity Object is initialized
     * Sub-class should invoke super.init() then:
     * entityCache.start(t)
     * useLocalEntityQueue() (if you want a local queue)
     ****************************************************
     */
    public void init()
    {
        entityQueue.start();          // Start Global Entity Queue
        //entityCache.start(30);      // Start Entity Cache
        //useLocalEntityQueue();      // Set and Start Local Entity Queue
    }

}

