/* vo_media_gen 
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import com.qkernel.*;

@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * A ValueObject for the db table media
 * @author Initially created by ValueObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class vo_media_gen extends CloneableObject
{

    /** mediaId database type:INT */
    public int mediaId=0;

    /** userId database type:INT */
    public int userId=0;

    /** mediaFile database type:VARCHAR */
    public String mediaFile="";

    /** mediaSource database type:VARCHAR */
    public String mediaSource="";

    /** mediaArtist database type:VARCHAR */
    public String mediaArtist="";

    /** mediaTitle database type:VARCHAR */
    public String mediaTitle="";

    /** mediaYear database type:VARCHAR */
    public String mediaYear="";

    /** mediaDuration database type:VARCHAR */
    public String mediaDuration="";

    /** mediaCreated database type:DATETIME */
    public String mediaCreated="";

    /** mediaModified database type:DATETIME */
    public String mediaModified="";

    /** mediaStatus database type:VARCHAR */
    public String mediaStatus="";

    /**
     * Gets a string representation of the requested field, or an empty string if not available
     * @param field - field name being requested (matching defined field name in the entity object)
     * @return String representation of the field requested
     */
    public String getString(String field)
    {
        if(field.equals(eo_media.FIELD_MEDIAID)) {return Integer.toString(mediaId);}
        if(field.equals(eo_media.FIELD_USERID)) {return Integer.toString(userId);}
        if(field.equals(eo_media.FIELD_MEDIAFILE)) {return mediaFile==null ? "" : mediaFile;}
        if(field.equals(eo_media.FIELD_MEDIASOURCE)) {return mediaSource==null ? "" : mediaSource;}
        if(field.equals(eo_media.FIELD_MEDIAARTIST)) {return mediaArtist==null ? "" : mediaArtist;}
        if(field.equals(eo_media.FIELD_MEDIATITLE)) {return mediaTitle==null ? "" : mediaTitle;}
        if(field.equals(eo_media.FIELD_MEDIAYEAR)) {return mediaYear==null ? "" : mediaYear;}
        if(field.equals(eo_media.FIELD_MEDIADURATION)) {return mediaDuration==null ? "" : mediaDuration;}
        if(field.equals(eo_media.FIELD_MEDIACREATED)) {return mediaCreated==null ? "" : mediaCreated;}
        if(field.equals(eo_media.FIELD_MEDIAMODIFIED)) {return mediaModified==null ? "" : mediaModified;}
        if(field.equals(eo_media.FIELD_MEDIASTATUS)) {return mediaStatus==null ? "" : mediaStatus;}
        return "";
    }

    /**
     * Sets the field value if it is available in the given Hashtable
     * @param values - list of fields and their associated values to be set
     */
    public void setFields(QMessage values)
    {
        if(values.containsKey(eo_media.FIELD_MEDIAID)) { mediaId = values.getInt(eo_media.FIELD_MEDIAID);}
        if(values.containsKey(eo_media.FIELD_USERID)) { userId = values.getInt(eo_media.FIELD_USERID);}
        if(values.containsKey(eo_media.FIELD_MEDIAFILE)) { mediaFile = values.getString(eo_media.FIELD_MEDIAFILE);}
        if(values.containsKey(eo_media.FIELD_MEDIASOURCE)) { mediaSource = values.getString(eo_media.FIELD_MEDIASOURCE);}
        if(values.containsKey(eo_media.FIELD_MEDIAARTIST)) { mediaArtist = values.getString(eo_media.FIELD_MEDIAARTIST);}
        if(values.containsKey(eo_media.FIELD_MEDIATITLE)) { mediaTitle = values.getString(eo_media.FIELD_MEDIATITLE);}
        if(values.containsKey(eo_media.FIELD_MEDIAYEAR)) { mediaYear = values.getString(eo_media.FIELD_MEDIAYEAR);}
        if(values.containsKey(eo_media.FIELD_MEDIADURATION)) { mediaDuration = values.getString(eo_media.FIELD_MEDIADURATION);}
        if(values.containsKey(eo_media.FIELD_MEDIACREATED)) { mediaCreated = values.getString(eo_media.FIELD_MEDIACREATED);}
        if(values.containsKey(eo_media.FIELD_MEDIAMODIFIED)) { mediaModified = values.getString(eo_media.FIELD_MEDIAMODIFIED);}
        if(values.containsKey(eo_media.FIELD_MEDIASTATUS)) { mediaStatus = values.getString(eo_media.FIELD_MEDIASTATUS);}
    }

}

