/* vo_upload_gen 
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import com.qkernel.*;

@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * A ValueObject for the db table upload
 * @author Initially created by ValueObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class vo_upload_gen extends CloneableObject
{

    /** uploadId database type:INT */
    public int uploadId=0;

    /** userId database type:INT */
    public int userId=0;

    /** uploadMetaData database type:MEDIUMBLOB */
    public String uploadMetaData="";

    /** uploadSource database type:VARCHAR */
    public String uploadSource="";

    /** uploadCreated database type:DATETIME */
    public String uploadCreated="";

    /** uploadModified database type:DATETIME */
    public String uploadModified="";

    /** uploadStatus database type:VARCHAR */
    public String uploadStatus="";

    /**
     * Gets a string representation of the requested field, or an empty string if not available
     * @param field - field name being requested (matching defined field name in the entity object)
     * @return String representation of the field requested
     */
    public String getString(String field)
    {
        if(field.equals(eo_upload.FIELD_UPLOADID)) {return Integer.toString(uploadId);}
        if(field.equals(eo_upload.FIELD_USERID)) {return Integer.toString(userId);}
        if(field.equals(eo_upload.FIELD_UPLOADMETADATA)) {return uploadMetaData==null ? "" : uploadMetaData;}
        if(field.equals(eo_upload.FIELD_UPLOADSOURCE)) {return uploadSource==null ? "" : uploadSource;}
        if(field.equals(eo_upload.FIELD_UPLOADCREATED)) {return uploadCreated==null ? "" : uploadCreated;}
        if(field.equals(eo_upload.FIELD_UPLOADMODIFIED)) {return uploadModified==null ? "" : uploadModified;}
        if(field.equals(eo_upload.FIELD_UPLOADSTATUS)) {return uploadStatus==null ? "" : uploadStatus;}
        return "";
    }

    /**
     * Sets the field value if it is available in the given Hashtable
     * @param values - list of fields and their associated values to be set
     */
    public void setFields(QMessage values)
    {
        if(values.containsKey(eo_upload.FIELD_UPLOADID)) { uploadId = values.getInt(eo_upload.FIELD_UPLOADID);}
        if(values.containsKey(eo_upload.FIELD_USERID)) { userId = values.getInt(eo_upload.FIELD_USERID);}
        if(values.containsKey(eo_upload.FIELD_UPLOADMETADATA)) { uploadMetaData = values.getString(eo_upload.FIELD_UPLOADMETADATA);}
        if(values.containsKey(eo_upload.FIELD_UPLOADSOURCE)) { uploadSource = values.getString(eo_upload.FIELD_UPLOADSOURCE);}
        if(values.containsKey(eo_upload.FIELD_UPLOADCREATED)) { uploadCreated = values.getString(eo_upload.FIELD_UPLOADCREATED);}
        if(values.containsKey(eo_upload.FIELD_UPLOADMODIFIED)) { uploadModified = values.getString(eo_upload.FIELD_UPLOADMODIFIED);}
        if(values.containsKey(eo_upload.FIELD_UPLOADSTATUS)) { uploadStatus = values.getString(eo_upload.FIELD_UPLOADSTATUS);}
    }

}

