/* vo_user_ugroup_gen 
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import com.qkernel.*;

@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * A ValueObject for the db table user_ugroup
 * @author Initially created by ValueObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class vo_user_ugroup_gen extends CloneableObject
{

    /** userId database type:INT */
    public int userId=0;

    /** ugroupId database type:INT */
    public int ugroupId=0;

    /**
     * Gets a string representation of the requested field, or an empty string if not available
     * @param field - field name being requested (matching defined field name in the entity object)
     * @return String representation of the field requested
     */
    public String getString(String field)
    {
        if(field.equals(eo_user_ugroup.FIELD_USERID)) {return Integer.toString(userId);}
        if(field.equals(eo_user_ugroup.FIELD_UGROUPID)) {return Integer.toString(ugroupId);}
        return "";
    }

    /**
     * Sets the field value if it is available in the given Hashtable
     * @param values - list of fields and their associated values to be set
     */
    public void setFields(QMessage values)
    {
        if(values.containsKey(eo_user_ugroup.FIELD_USERID)) { userId = values.getInt(eo_user_ugroup.FIELD_USERID);}
        if(values.containsKey(eo_user_ugroup.FIELD_UGROUPID)) { ugroupId = values.getInt(eo_user_ugroup.FIELD_UGROUPID);}
    }

}

