/* vo_ugroup_permission_gen 
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import com.qkernel.*;

@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * A ValueObject for the db table ugroup_permission
 * @author Initially created by ValueObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class vo_ugroup_permission_gen extends CloneableObject
{

    /** ugroupId database type:INT */
    public int ugroupId=0;

    /** permissionId database type:INT */
    public int permissionId=0;

    /**
     * Gets a string representation of the requested field, or an empty string if not available
     * @param field - field name being requested (matching defined field name in the entity object)
     * @return String representation of the field requested
     */
    public String getString(String field)
    {
        if(field.equals(eo_ugroup_permission.FIELD_UGROUPID)) {return Integer.toString(ugroupId);}
        if(field.equals(eo_ugroup_permission.FIELD_PERMISSIONID)) {return Integer.toString(permissionId);}
        return "";
    }

    /**
     * Sets the field value if it is available in the given Hashtable
     * @param values - list of fields and their associated values to be set
     */
    public void setFields(QMessage values)
    {
        if(values.containsKey(eo_ugroup_permission.FIELD_UGROUPID)) { ugroupId = values.getInt(eo_ugroup_permission.FIELD_UGROUPID);}
        if(values.containsKey(eo_ugroup_permission.FIELD_PERMISSIONID)) { permissionId = values.getInt(eo_ugroup_permission.FIELD_PERMISSIONID);}
    }

}

