/* eo_user_ugroup_gen.java
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import java.lang.*;
import java.sql.*;
import java.util.*;

import com.qkernel.*;


@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * An entity object for the db table user_ugroup
 * 
 * 
 * @author Initially created by EntityObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class eo_user_ugroup_gen extends EntityObject
{

    public final static String FIELD_USERID = "userId";
    public final static String FIELD_UGROUPID = "ugroupId";

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_user_ugroup object with the data, 
     * @param rs A result set of a query on the user_ugroup table
     *****************************************************
     */
     public void setEntity(ResultSet rs, ArrayList al) throws SQLException
     {
         vo_user_ugroup e = entityRow(rs);
         al.add(e);
     }

    /*****************************************************
     * This function takes the current row in a ResultSet,
     * creates a vo_user_ugroup object with the data, 
     * @param rs A result set of a query on the user_ugroup table
     *****************************************************
     */
     public void setEntityV(ResultSet rs, Vector vec) throws SQLException
     {
         vo_user_ugroup e = entityRow(rs);
         vec.addElement(e);
     }

    /****************************************************
     * This function maps an SQL row to a Value Object
     *
     * @param rs a ResultSet that contains the record to be mapped
     * @return a vo_user_ugroup value object
     ****************************************************
     */
    public vo_user_ugroup entityRow(ResultSet rs) throws SQLException
    {
        vo_user_ugroup e = new vo_user_ugroup();
        e.userId= rs.getInt(FIELD_USERID);
        e.ugroupId= rs.getInt(FIELD_UGROUPID);
        return(e);
    }

    /****************************************************
     * This method inserts a new record into the table,
     * but DOES NOT return the new ID or a reference object
     * @param vo_user_ugroup a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insert(vo_user_ugroup e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO user_ugroup(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_UGROUPID+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("").append(e.ugroupId).append(")");


        executeUpdate(qsb.toString());
    }

    /****************************************************
     * This method inserts a new record into the table,
     * using the local entityQueue
     * @param vo_user_ugroup a value object to be written
     *  to the DB
     * @see #insert2()
     ****************************************************
     */
    public void insertQueue(vo_user_ugroup e){
        StringBuffer qsb=new StringBuffer();
        qsb.append("INSERT INTO user_ugroup(");
        qsb.append(FIELD_USERID+",");
        qsb.append(FIELD_UGROUPID+")");
        qsb.append("VALUES(");
        qsb.append("").append(e.userId).append(",");
        qsb.append("").append(e.ugroupId).append(")");


        entityQueue.put(qsb.toString());
    }

    /****************************************************
     * This function is called by the daemon when this 
     * Entity Object is initialized
     * Sub-class should invoke super.init() then:
     * entityCache.start(t)
     * useLocalEntityQueue() (if you want a local queue)
     ****************************************************
     */
    public void init()
    {
        entityQueue.start();          // Start Global Entity Queue
        //entityCache.start(30);      // Start Entity Cache
        //useLocalEntityQueue();      // Set and Start Local Entity Queue
    }

}

