/* vo_ugroup_gen 
 *
 * THE FOLLOWING CODE IS AUTO GENERATED BY GENDB SCRIPT 
 * !!!!!!!!!!!!  DO NOT MODIFY THIS FILE !!!!!!!!!!!
 */
package com.qkernel.examples.model;

import com.qkernel.*;

@SuppressWarnings({"unchecked", "fallthrough", "serial" })
/************************************************************
 * A ValueObject for the db table ugroup
 * @author Initially created by ValueObjectBuilder
 * @version $Revision$ 
 ************************************************************
 */
public abstract class vo_ugroup_gen extends CloneableObject
{

    /** ugroupId database type:INT */
    public int ugroupId=0;

    /** ugroupName database type:VARCHAR */
    public String ugroupName="";

    /**
     * Gets a string representation of the requested field, or an empty string if not available
     * @param field - field name being requested (matching defined field name in the entity object)
     * @return String representation of the field requested
     */
    public String getString(String field)
    {
        if(field.equals(eo_ugroup.FIELD_UGROUPID)) {return Integer.toString(ugroupId);}
        if(field.equals(eo_ugroup.FIELD_UGROUPNAME)) {return ugroupName==null ? "" : ugroupName;}
        return "";
    }

    /**
     * Sets the field value if it is available in the given Hashtable
     * @param values - list of fields and their associated values to be set
     */
    public void setFields(QMessage values)
    {
        if(values.containsKey(eo_ugroup.FIELD_UGROUPID)) { ugroupId = values.getInt(eo_ugroup.FIELD_UGROUPID);}
        if(values.containsKey(eo_ugroup.FIELD_UGROUPNAME)) { ugroupName = values.getString(eo_ugroup.FIELD_UGROUPNAME);}
    }

}

